version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.2

parameters:
  environment:
    type: enum
    enum: ["stage", "prod"]
    default: "stage"
    description: "Choose the environment to run tests on (stage or prod)."

jobs:
  run-tests:
    executor: cypress/default
    parameters:
      environment:
        type: enum
        enum: ["stage", "prod"]
        default: "stage"
    resource_class: large  # Allocate more resources for long-running tests    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
          no_output_timeout: 30m  # Ensures the step doesn’t timeout due to inactivity
      - run:
          name: Run Cypress Tests
          command: |
            if [ "<< parameters.environment >>" = "stage" ]; then
              npx cypress run --spec "cypress/e2e/Tumbledry/Store_detail.js"
            else
              npx cypress run --spec "cypress/e2e/Cambaytiger/prod/*.js"
            fi
          no_output_timeout: 30m  # Ensures the Cypress test execution doesn’t timeout due to inactivity
      - store_artifacts:
          path: cypress/reports
          destination: test-report

workflows:
  version: 2
  run-tests-workflow:
    jobs:
      - run-tests:
          environment: << pipeline.parameters.environment >>
