version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.2

jobs:
  custom-cypress-run:
    docker:
      - image: cypress/included:latest  # Using Cypress official image with Chrome preinstalled
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run --spec "cypress/e2e/Cambaytiger/stage/404.js" --disable-gpu
      - store_artifacts:
          path: cypress/reports
          destination: test-report

workflows:
  version: 2
  build:
    jobs:
      - custom-cypress-run:
          timeout: 30m  # Set the timeout at the workflow level for this job
