version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.2

workflows:
  version: 2
  build:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --spec "cypress/e2e/Cambaytiger/stage/404.js,cypress/e2e/Cambaytiger/stage/404-2.js"
          post-steps:
            - store_artifacts:
                path: cypress/reports
                destination: test-report
