version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.2

parameters:
  environment:
    type: enum
    enum: ["stage", "prod"]
    default: "stage"
    description: "Choose the environment to run tests on (stage or prod)."

jobs:
  run-tests:
    executor: cypress/default
    parameters:
      environment:
        type: enum
        enum: ["stage", "prod"]
        default: "stage"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: |
            if [ "<< parameters.environment >>" = "stage" ]; then
              npx c
