version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.2

workflows:
  version: 2
  build:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --spec "cypress/e2e/Cambaytiger/stage/404.js"
          executor:
            name: cypress/default
            timeout: 30m # Set job timeout to 30 minutes
          post-steps:
            - store_artifacts:
                path: cypress/reports
                destination: test-report
