version: 2.1

jobs:
  install-dependencies:
    docker:
      - image: cypress/base:14  # Use Node.js 14 or higher for optional chaining compatibility
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install

  run-tests:
    docker:
      - image: cypress/base:14
    steps:
      - checkout
      - run:
          name: Run Cypress Tests
          command: npx cypress run --headed --spec "cypress/e2e/Cambaytiger/stage/Search.js"
          
workflows:
  version: 2
  test-workflow:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
