version: 2.1

jobs:
  install-dependencies:
    docker:
      - image: cypress/base:12  # Use an appropriate Cypress Docker image
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install

  run-tests:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      - run:
          name: Set test specifications
          # command: |
          #   if [ "${CIRCLE_BRANCH}" == "stage" ]; then
          #     export TEST_SPEC="cypress/e2e/Plixlife/stage/Search.js,cypress/e2e/Plixlife/stage/Booking.js,cypress/e2e/Cambaytiger/stage/Search.js,cypress/e2e/Cambaytiger/stage/Booking.js"
          #   else
          #     export TEST_SPEC="cypress/e2e/Plixlife/prod/Search.js,cypress/e2e/Plixlife/prod/Booking.js,cypress/e2e/Cambaytiger/prod/Search.js,cypress/e2e/Cambaytiger/prod/Booking.js"
          #   fi
      - run:
          name: Run Cypress Tests
          # command: npx cypress run --headed --spec "${TEST_SPEC}"
          command: npx cypress run --headed --spec "cypress/e2e/Cambaytiger/stage/Search.js"
          

workflows:
  version: 2
  test-workflow:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
