version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.2

parameters:
  environment:
    type: enum
    enum: ["stage", "prod"]
    default: "stage"
    description: "Choose the environment to run tests on (stage or prod)."

jobs:
  run-tests:
    executor: cypress/default
    parameters:
      environment:
        type: enum
        enum: ["stage", "prod"]
        default: "stage"
    resource_class: large
    parallelism: 2  # Number of parallel containers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress Tests in Parallel
          command: |
            case $CIRCLE_NODE_INDEX in
              0) npx cypress run --spec "cypress/e2e/Tumbledry/Test.js";;
              1) npx cypress run --spec "cypress/e2e/Tumbledry/Test-mobile.js";;
              *) echo "No test file assigned to this container";;
            esac
      - store_artifacts:
          path: cypress/reports
          destination: test-report
      - store_test_results:
          path: cypress/reports

workflows:
  version: 2
  run-tests-workflow:
    jobs:
      - run-tests:
          environment: << pipeline.parameters.environment >>
