version: 2.1

jobs:
  install-dependencies:
    docker:
      - image: node:19  # Node.js 19 image
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: npm install cypress@latest
      - run:
          name: Verify Cypress Installation
          command: npx cypress verify

  run-tests:
    docker:
      - image: node:19
    steps:
      - checkout
      - run:
          name: Run Cypress Tests
          command: npx cypress run --headed --spec "cypress/e2e/Cambaytiger/stage/Search.js"

workflows:
  version: 2
  test-workflow:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
