version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2

workflows:
  version: 2
  build:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --env viewportWidth=1000,viewportHeight=660 --headed --spec "cypress/e2e/Cambaytiger/stage/Booking.js"


