version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.2

workflows:
  version: 2
  build:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --spec "cypress/e2e/Cambaytiger/stage/404-1.js,cypress/e2e/Cambaytiger/stage/404-2.js,cypress/e2e/Cambaytiger/stage/404-3.js,cypress/e2e/Cambaytiger/stage/404-4.js,cypress/e2e/Cambaytiger/stage/404-5.js,cypress/e2e/Cambaytiger/stage/404-6.js,cypress/e2e/Cambaytiger/stage/404-7.js,cypress/e2e/Cambaytiger/stage/404-8.js,cypress/e2e/Cambaytiger/stage/404-9.js,cypress/e2e/Cambaytiger/stage/404-10.js,"
          post-steps:
            - store_artifacts:
                path: cypress/reports
                destination: test-report
