version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2
workflows:
  build:
    jobs:
      - cypress/run:          
          cypress-command: npx cypress run --spec "cypress/e2e/Cambaytiger/stage/Booking.js,cypress/e2e/Cambaytiger/stage/Search.js"

