version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2

workflows:
  version: 2
  build:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --headed --spec "cypress/e2e/Cambaytiger/stage/Booking.js"

jobs:
  persist-artifacts:
    docker:
      - image: cypress/base:latest
    steps:
      - run:
          name: Run Cypress Tests
          command: npx cypress run --headed  --spec "cypress/e2e/Cambaytiger/stage/Booking.js"
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/videos
          destination: videos
