version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  cypress_run:
    docker:
      - image: cypress/included:12.8.0 # or any other compatible Cypress image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - cypress/run:
          yarn: true

workflows:
  version: 2
  build:
    jobs:
      - cypress_run
