version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2
workflows:
  build:
    jobs:
      - cypress/run:
          browser: electron
          spec: "cypress/e2e/Cambaytiger/stage/Search.js"
          record: false
          config: "video=true"
          headless: false  # This should enforce headed mode
